spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SocialMediaAnalysis
    username: cs5330
    password: pw5330
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        namingStrategy: EJB3NamingStrategy
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always